openapi: 3.0.3
info:
  title: EasyShop-Catalog
  contact:
    name: API Support
    url: https://ensi.tech/contacts
    email: mail@greensight.ru
  version: 1.0.0
  description: EasyShop-Catalog
servers:
  - url: /api/v1
tags:
  - name: Catalogs
    description: catalog
paths:
  /examples/{id}:
    get:
      tags:
        - catalog
      operationId: createCatalog
      x-lg-handler: 'App\Http\ApiV1\Modules\Catalog\Controllers\CatalogController'
      summary: Создание обьекта типа каталог
      description: Создание обьекта типа каталог
      parameters:
        - $ref: '#/components/parameters/PathId'
        - $ref: '#/components/parameters/QueryInclude'
      responses:
        #"200":
          #description: Успешный ответ
          # content:
          #  application/json:
          #    schema:
          #      $ref: './customers.yaml#/CustomerResponse'
        "404":
          $ref: '#/components/responses/NotFound'
        "500":
          $ref: '#/components/responses/ServerError'
components:
  parameters:
    QueryInclude:
      $ref: './common_parameters.yaml#/QueryInclude'
    PathId:
      $ref: './common_parameters.yaml#/PathId'
  schemas:
    EmptyDataResponse:
      type: object
      properties:
        data:
          type: object
          nullable: true
        meta:
          type: object
      required:
          - data
    PaginationTypeEnum:
      $ref: './common_schemas.yaml#/PaginationTypeEnum'
  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: './errors.yaml#/ErrorResponse'
    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: './errors.yaml#/ErrorResponse'
    ServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: './errors.yaml#/ErrorResponse'
